services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - broker
      - mongodb
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/promoproject?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=broker:9092
      - SPRING_KAFKA_TEMPLATE_DEFAULT_TOPIC=my-topic
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin123@mongodb:27017/promoproject?authSource=admin
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      # KRaft Specifics
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Networking - Use 0.0.0.0 to bind, service name to advertise
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # Reliability
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080" # Note: UI inside latest image usually runs on 8080
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      # This helps UI wait for the cluster to be ready
      DYNAMIC_CONFIG_ENABLED: 'true'
    restart: on-failure

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    command: ["--kafka.server=broker:9092"]
    ports:
      - "9308:9308"
    depends_on:
      - broker
    restart: always # Crucial: forces it to retry until Kafka is up

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb-data:/data/db

  mongodb-exporter:
    image: percona/mongodb_exporter:0.40
    command: ["--mongodb.uri=mongodb://admin:admin123@mongodb:27017/admin"]
    ports:
      - "9216:9216"
    depends_on:
      - mongodb

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
      - kafka-exporter
      - mongodb-exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  mongodb-data:
  kafka-data:
  grafana-data: