spring:
  application:
    name: promo-project-app

  # Kafka Configuration
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: promo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # MongoDB Configuration
  data:
    mongodb:
      # Format: mongodb://user:password@service-name:port/database?authSource=admin
      uri: mongodb://admin:admin123@mongodb:27017/promoproject?authSource=admin

# Actuator & Prometheus Metrics Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
